### ISSUE TITLE
Link broken to "Part 1: Azure Databricks and its integration with Azure Machine Learning Services"

### ISSUE THREAD

**Issue by bartczernicki** [Azure/LearnAI-CustomAI-Airlift#2]
Link on bottom of this page: https://azure.github.io/LearnAI-CustomAI-Airlift/

"Part 1: Azure Databricks and its integration with Azure Machine Learning Services" is broken.

**Comment by wmpauli** [comment]
Sorry for the late response. We did a major overall of the repo. The link is now removed. You can find the databricks archive of the notebooks in the "presenter" folder, and individual notebooks in the "notebooks" folder. Please let us know if you are still having issues.
